version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: telemetry
      RABBITMQ_DEFAULT_PASS: telemetry
    ports:
    - "15672:15672"


  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
    - "8086:8086"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: telemetry
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: telemetry
      INFLUXDB_USER_PASSWORD: telemetry
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
    - /data/influxdb/data:/var/lib/influxdb

  chronograf:
    image: chronograf:alpine
    volumes:
    - /data/chronograf:/var/lib/chronograf
    ports:
    - "8888:8888"
    links:
    - influxdb