version: "3"

services:

  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: telemetry
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: telemetry
      INFLUXDB_USER_PASSWORD: telemetry
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
    - /data/influxdb/data:/var/lib/influxdb

  chronograf:
    image: chronograf:alpine
    volumes:
    - /data/chronograf:/var/lib/chronograf
    ports:
    - "8888:8888"
    links:
    - influxdb