version: "3"

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: pb
      RABBITMQ_DEFAULT_PASS: pb
    ports:
    - "5672:5672"
    - "15672:15672"


  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
    - "8086:8086"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: pb
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: pb
      INFLUXDB_USER_PASSWORD: pb
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
    - /data/influxdb/data:/var/lib/influxdb

  chronograf:
    image: chronograf:alpine
    volumes:
    - /data/chronograf:/var/lib/chronograf
    ports:
    - "8888:8888"
    links:
    - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000"
    volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
    - /srv/docker/grafana/data:/var/lib/grafana