dependencies:
- name: influxdb
  version: 0.9.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: chronograf
  version: 0.4.5
  repository: https://kubernetes-charts.storage.googleapis.com/
