deployment:
  ## Annotations to be added to the Service
  ##
  annotations: {}

  terminationGracePeriodSeconds: 30

  affinity: {}

  tolerations: []

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

  ## Node selector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  nodeSelector: {}

  image:
    repository: hub.docker.com/batazor/go-logger
    tag: latest

    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: Always

  env:
    AMQP_API:
    AMQP_NAME_QUEUE:
    AMQP_EXCHANGE_LIST:
    DB_URL:
    DB_NAME:
    DB_USERNAME:
    DB_PASSWORD:

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # limits:
    #   cpu: 300m
    #   memory: 300Mi
    # requests:
    #   cpu: 100m
    #   memory: 300Mi



  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:

    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi
    hostPath: /data/mysql

  ## Configure extra options for liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

service:
  ## Kubernetes service type
  type: NodePort

  ## Port to expose on each node
  ## Only used if service.type is 'NodePort'
  ##
  nodePort: 8080
