deployment:
  ## Annotations to be added to the Service
  ##
  annotations: {}

  terminationGracePeriodSeconds: 30

  affinity: {}

  tolerations: []

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

  ## Node selector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  nodeSelector: {}

  image:
    repository: hub.docker.com/batazor/go-logger
    tag: latest

    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: Always

  env:
    AMQP_API:
    AMQP_NAME_QUEUE:
    AMQP_EXCHANGE_LIST:
    DB_URL:
    DB_NAME:
    DB_USERNAME:
    DB_PASSWORD:

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 100Mi

  ## Configure extra options for liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

service:
  ## Kubernetes service type
  type: NodePort

  ## Port to expose on each node
  ## Only used if service.type is 'NodePort'
  ##
  nodePort: 8080

influxdb:
  ## influxdb image version
  ## ref: https://hub.docker.com/r/library/influxdb/tags/
  image:
    tag: 1.6-alpine

  env:
    INFLUXDB_ADMIN_ENABLED: "true"
    INFLUXDB_DB: telemetry
    INFLUXDB_ADMIN_USER: admin
    INFLUXDB_ADMIN_PASSWORD: admin
    INFLUXDB_USER: telemetry
    INFLUXDB_USER_PASSWORD: telemetry
    INFLUXDB_DATA_ENGINE: tsm1
    INFLUXDB_REPORTING_DISABLED: "false"

  ## Change InfluxDB configuration parameters below:
  ## Defaults are indicated
  ## ref: https://docs.influxdata.com/influxdb/v1.1/administration/config/
  config:
#    reporting_disabled: false
#    bind_address: 8088
#    storage_directory: /var/lib/influxdb
#    meta:
#      retention_autocreate: true
#      logging_enabled: true
#    data:
#      query_log_enabled: true
#      cache_max_memory_size: 1073741824
#      cache_snapshot_memory_size: 26214400
#      cache_snapshot_write_cold_duration: 10m0s
#      compact_full_write_cold_duration: 4h0m0s
#      max_series_per_database: 1000000
#      max_values_per_tag: 100000
#      trace_logging_enabled: false
#    coordinator:
#      write_timeout: 10s
#      max_concurrent_queries: 0
#      query_timeout: 0s
#      log_queries_after: 0s
#      max_select_point: 0
#      max_select_series: 0
#      max_select_buckets: 0
#    retention:
#      enabled: true
#      check_interval: 30m0s
#    shard_precreation:
#      enabled: true
#      check_interval: 10m0s
#      advance_period: 30m0s
#    admin:
#      enabled: false
#      bind_address: 8083
#      https_enabled: false
#      https_certificate: /etc/ssl/influxdb.pem
#    monitor:
#      store_enabled: true
#      store_database: _internal
#      store_interval: 10s
#    subscriber:
#      enabled: true
#      http_timeout: 30s
#      insecure_skip_verify: false
#      ca_certs: ""
#      write_concurrency: 40
#      write_buffer_size: 1000
#    http:
#      enabled: true
#      bind_address: 8086
#      auth_enabled: false
#      log_enabled: true
#      write_tracing: false
#      pprof_enabled: true
#      https_enabled: false
#      https_certificate: /etc/ssl/influxdb.pem
#      https_private_key: ""
#      max_row_limit: 10000
#      max_connection_limit: 0
#      shared_secret: "beetlejuicebeetlejuicebeetlejuice"
#      realm: InfluxDB
#      unix_socket_enabled: false
#      bind_socket: /var/run/influxdb.sock
#    graphite:
#      enabled: false
#      bind_address: 2003
#      database: graphite
#      retention_policy: autogen
#      protocol: tcp
#      batch_size: 5000
#      batch_pending: 10
#      batch_timeout: 1s
#      consistency_level: one
#      separator: .
#      udp_read_buffer: 0
#      # Uncomment to define graphite templates
#      # templates:
#      #   - "graphite.metric.*.*.* measurement.run"
#    collectd:
#      enabled: false
#      bind_address: 25826
#      database: collectd
#      retention_policy: autogen
#      batch_size: 5000
#      batch_pending: 10
#      batch_timeout: 10s
#      read_buffer: 0
#      typesdb: /usr/share/collectd/types.db
#      security_level: none
#      auth_file: /etc/collectd/auth_file
#    opentsdb:
#      enabled: false
#      bind_address: 4242
#      database: opentsdb
#      retention_policy: autogen
#      consistency_level: one
#      tls_enabled: false
#      certificate: /etc/ssl/influxdb.pem
#      batch_size: 1000
#      batch_pending: 5
#      batch_timeout: 1s
#      log_point_errors: true
#    udp:
#      enabled: false
#      bind_address: 8089
#      database: udp
#      retention_policy: autogen
#      batch_size: 5000
#      batch_pending: 10
#      read_buffer: 0
#      batch_timeout: 1s
#      precision: "ns"
#    continuous_queries:
#      log_enabled: true
#      enabled: true
#      run_interval: 1s
