apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "logger.fullname" . }}
  labels:
    app: {{ template "logger.name" . }}
    chart: {{ template "logger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  serviceName: {{ template "logger.fullname" . }}
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: 2
  updateStrategy:
    type: {{ .Values.deployment.updateStrategy }}
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "logger.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "logger.name" . }}
        chart: {{ template "logger.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    annotations:
      {{- range $key, $value := .Values.deployment.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
{{- if and .Values.prometheus.exporter.enabled  (not .Values.prometheus.operator.enabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.exporter.port | quote }}
{{- end }}
      labels:
        app: {{ template "logger.name" . }}
        release: "{{ .Release.Name }}"
        chart: {{ template "logger.chart" . }}
    spec:
      serviceAccountName: {{ template "logger.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      {{- if .Values.deployment.nodeSelector }}
      securityContext:
        {{ toYaml .Values.securityContext | indent 8 }}
      nodeSelector:
 {{ toYaml .Values.deployment.nodeSelector | indent 8 }}
       {{- end }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      {{- with .Values.deployment.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.deployment.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.deployment.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy | quote }}
        {{- if .Values.args }}
        args:
{{ toYaml .Values.args | indent 10 }}
        {{- end }}
        env:
{{- range $key, $value := .Values.deployment.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
        ports:
        - name: exporter
          protocol: TCP
          containerPort: {{ .Values.prometheus.exporter.port }}
        {{- if .Values.deployment.livenessProbe.enabled }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
          exec:
            command:
            - echo 0
        {{- end }}
        {{- if .Values.deployment.livenessProbe.enabled }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
          exec:
            command:
            - echo 0
        {{- end }}
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
