apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  name: {{ template "logger.fullname" . }}
  labels:
    app: {{ template "logger.name" . }}
    chart: {{ template "logger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{ if .Values.prometheus.exporter.enabled }}
  - name: exporter
    protocol: TCP
    port: {{ .Values.prometheus.exporter.port }}
    targetPort: exporter
  {{ end }}
  selector:
    app: {{ template "logger.name" . }}
    release: "{{ .Release.Name }}"
