{{ if and .Values.prometheus.exporter.enabled .Values.prometheus.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "logger.fullname" . }}
  namespace: {{ .Values.prometheus.operator.serviceMonitor.namespace }}
  labels:
    {{ template "logger.fullname" . }}-client: "true"
{{- if .Values.prometheus.operator.serviceMonitor.selector }}
{{ toYaml .Values.prometheus.operator.serviceMonitor.selector | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "logger.name" . }}
      release: {{ .Release.Name }}
  endpoints:
  - port: exporter
    interval: {{ .Values.prometheus.operator.serviceMonitor.interval }}
  namespaceSelector:
    any: true
{{ end }}
